export type PrimitiveSection = '基础' | '导航' | '输入' | '数据展示' | '反馈' | '浮层' | '布局';
export type PrimitiveManifestItem = { name: string; file: string; section: PrimitiveSection };

export const primitiveManifest: PrimitiveManifestItem[] = [
  { name: 'Button', file: 'button', section: '基础' }, { name: 'Badge', file: 'badge', section: '基础' }, { name: 'Card', file: 'card', section: '基础' }, { name: 'Alert', file: 'alert', section: '反馈' }, { name: 'Avatar', file: 'avatar', section: '基础' }, { name: 'Checkbox', file: 'checkbox', section: '输入' }, { name: 'Input', file: 'input', section: '输入' }, { name: 'Input OTP', file: 'input-otp', section: '输入' }, { name: 'Label', file: 'label', section: '输入' }, { name: 'Radio Group', file: 'radio-group', section: '输入' }, { name: 'Select', file: 'select', section: '输入' }, { name: 'Slider', file: 'slider', section: '输入' }, { name: 'Switch', file: 'switch', section: '输入' }, { name: 'Textarea', file: 'textarea', section: '输入' }, { name: 'Toggle', file: 'toggle', section: '输入' }, { name: 'Toggle Group', file: 'toggle-group', section: '输入' },
  { name: 'Accordion', file: 'accordion', section: '导航' }, { name: 'Breadcrumb', file: 'breadcrumb', section: '导航' }, { name: 'Collapsible', file: 'collapsible', section: '导航' }, { name: 'Command', file: 'command', section: '导航' }, { name: 'Menubar', file: 'menubar', section: '导航' }, { name: 'Navigation Menu', file: 'navigation-menu', section: '导航' }, { name: 'Pagination', file: 'pagination', section: '导航' }, { name: 'Sidebar', file: 'sidebar', section: '导航' }, { name: 'Tabs', file: 'tabs', section: '导航' }, { name: 'Tooltip', file: 'tooltip', section: '导航' },
  { name: 'Calendar', file: 'calendar', section: '数据展示' }, { name: 'Chart', file: 'chart', section: '数据展示' }, { name: 'Progress', file: 'progress', section: '数据展示' }, { name: 'Table', file: 'table', section: '数据展示' }, { name: 'Skeleton', file: 'skeleton', section: '数据展示' },
  { name: 'Alert Dialog', file: 'alert-dialog', section: '浮层' }, { name: 'Context Menu', file: 'context-menu', section: '浮层' }, { name: 'Dialog', file: 'dialog', section: '浮层' }, { name: 'Drawer', file: 'drawer', section: '浮层' }, { name: 'Dropdown Menu', file: 'dropdown-menu', section: '浮层' }, { name: 'Hover Card', file: 'hover-card', section: '浮层' }, { name: 'Popover', file: 'popover', section: '浮层' }, { name: 'Sheet', file: 'sheet', section: '浮层' }, { name: 'Toast', file: 'sonner', section: '反馈' },
  { name: 'Aspect Ratio', file: 'aspect-ratio', section: '基础' }, { name: 'Carousel', file: 'carousel', section: '数据展示' }, { name: 'Form', file: 'form', section: '输入' }, { name: 'Resizable', file: 'resizable', section: '布局' }, { name: 'Scroll Area', file: 'scroll-area', section: '基础' }, { name: 'Separator', file: 'separator', section: '基础' },
];
